### ISSUE TITLE
Merge gh-pages

### ISSUE THREAD

**Issue by nokout** [AusDTO/biz_gov#3]
Hey @cam-grant  can we merge the changes in gh-pages branch?

I did a temporary change to get a readme up on the repo but would much prefer to get your changes merged. Looks like you put a fair amount of effort into them. Are they in a stable state where we can merge them?

Cheers, Nigel

**Comment by cam-grant** [comment]
Hey Nigel - sure - merge my latest if your repo isn't up to date. This project was completed a couple months ago, so no changes since then, should be stable.

I just switched my repo's default branch to gh-pages - master is out of date and not relevant.

-Cam

**Comment by nokout** [comment]
Great thanks cam I will merge when I get a chance. Cheers, Nigel
